## Orthogonal Complements

Resource: https://www.youtube.com/watch?v=ZIzB2LmXs0c&ab_channel=STEMSupport

In [1]:
import numpy as np
from sympy import Matrix, symbols, Eq, solve_linear_system
from scipy.linalg import null_space

In [2]:
V1= np.array([[1],
             [7],
             [2]])

V2= np.array([[-2],
             [3],
             [1]])

In [43]:
V = np.array([
    [1, 7, 2],
    [-2, 3, 1]
])
V_matrix = Matrix(V)
rref_matrix, pivot_cols = V_matrix.rref()
display(rref_matrix)

Matrix([
[1, 0, -1/17],
[0, 1,  5/17]])

In [48]:
solveV = np.array([[1],
                  [-5],
                  [17]])

np.dot(V1.T, solveV)  # the dot product yields 0 which confirms our solution is solved

array([[0]])

### Compute the Orthogonal Complement

1. find the transpose of the two arrays
2. create a matrix out of the two arrays
3. Row reduce to simplify the matrices
4. Set up and solve a system of linear equations
5. Verify the result by taking the dot product of the output against one of the transposed arrays

### Example problem: 3 dimensional matrix

In [51]:
# define our vector arrays
# from here we need to transpose each vector then concatenate them together before we row reduce
W1 = np.array([
    [1],
    [0],
    [2],
    [3]
])

W2 = np.array([
    [2],
    [1],
    [0],
    [-1]
])

In [64]:
# concatenate the vectors together
W = np.concatenate((W1.T,W2.T), axis=0)
display(W)
z = np.array([[0],
         [0]])

W_sys = np.concatenate((W, z), axis=1)
display(W_sys)

array([[ 1,  0,  2,  3],
       [ 2,  1,  0, -1]])

array([[ 1,  0,  2,  3,  0],
       [ 2,  1,  0, -1,  0]])

In [59]:
# row reduce the matrix
W_matrix = Matrix(W)
rref_matrix, pivot_cols = W_matrix.rref()
display(rref_matrix)

Matrix([
[1, 0,  2,  3],
[0, 1, -4, -7]])

Solve $Vx=0$ to find the set of vectors orthogonal to both v1 and v2

In [65]:
# define the variables
x1, x2, x3, x4 = symbols('x1 x2 x3 x4')
# solve the system
solution = solve_linear_system(W_sys, x1, x2, x3, x4)
display(solution)

{x1: -2*x3 - 3*x4, x2: 4*x3 + 7*x4}

## Workspace

In [4]:
B = np.array([
    [1, 1, -1],
    [1, 1, 1]
])
bMatrix = Matrix(B)
rref_matrix, pivot_cols = bMatrix.rref()
display(rref_matrix)

Matrix([
[1, 1, 0],
[0, 0, 1]])